### ISSUE TITLE
Add CreateNoWindow = true feature

### ISSUE THREAD

**Issue by Kvikku** [basicx-StrgV/WGet.NET#6] opened 2022-11-28 12:28 UTC
Hi. Would it be possible to add the following launch property to the winget executable?

CreateNoWindow = true

Or some similar functionality to prevent a cmd window from appearing whenever the winget commands run?

**Comment by basicx-StrgV** [comment] 2022-11-28 19:07
Hello,
this behavior is not intentional, the process window should already be hidden.
I will have to look into this. 
Can you please tell me the version number of the library where this problem occurred?
Do you know if this problem occurs with every command or just some of the commands?

**Comment by Kvikku** [comment] 2022-11-29 07:06
I am running version 2.0.2. 

I made a simple app with some of the examples you provided, such as:

WinGetPackageManager packageManager = new WinGetPackageManager();

packageManager.InstallPackage(Google.Chrome);

Everytime this runs a cmd window appears for a brief moment (~1 second), before it closes and the result from the command is returned.

**Comment by basicx-StrgV** [comment] 2022-11-29 17:05
Thank you, I will look into it.

**Comment by basicx-StrgV** [comment] 2023-04-22 13:23
Sorry for the extremely long wait, I already had some changes ready but forgot to publish them, because I had some other things going on.

I was not able to reproduce the problem, but I changed the process execution settings, in the newest version.

If you are still interested and have the time, check out version 2.0.3 and test if the problem still exists.

https://github.com/basicx-StrgV/WGet.NET/releases/tag/2.0.3

**Comment by basicx-StrgV** [comment] 2023-08-15 20:01
I will close the issue for now. If the issue still persists, please feel free to open a new issue .

**Closed as completed by basicx-StrgV** 2023-08-15 20:01 UTC
Labels: bug
