### ISSUE TITLE
.Net Standard Support

### ISSUE THREAD

**Issue by MrHinsh** [basicx-StrgV/WGet.NET#15] opened 2023-10-10 09:07 UTC
It would be great if you could support .NET standard! 

My application MUST use .NET 4 as it uses Microsoft libraries that are full framework :( but I have most of my libraries set to ".NET Standard" so that I can use them in both core and full framework where necessary.

**Comment by basicx-StrgV** [comment] 2023-10-11 19:33
I understand the problem that this library is not compatible with older framework versions.  
But I will probably not switch the library from .Net Core 3.1 to .Net Standard 2.0.  


.Net Standard will not get any major updates (https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/) but it is needed for the transitioning time from .Net Framework to .Net Core (Now only .Net).  
I also work with software that only supports .Net Framework 4.x and understand the problem at hand .


.Net Core 3.1 gives me compatibility with all new framework versions and allows me to more easily update to the newes LTS version (Like .Net 6 or 8), when necessary.  
This allows me to have the library more future proof.

I could create a .Net Standard version of the library, but I’m not sure if I can and want to support two different framework versions of the library, because I only work on it in my free time.

**I need to think about this problem a bit, to hopefully find a good solution.  
I will post updates to this issue, when I have found a possible solution.**

**Comment by basicx-StrgV** [comment] 2023-10-13 15:29
I released a pre-release version of the library that now also has support for .Net Standard 2.0.
The basic functionalities should now work in .Net Standard 2.0 but async execution is currently not supported.

https://github.com/basicx-StrgV/WGet.NET/releases/tag/3.0.0-alpha1

I will continue to  work on this feature to improve its functionalities and publish new versions when they are ready.

**Comment by basicx-StrgV** [comment] 2023-10-13 21:57
I published a second pre-release version that now fully supports all asynchronous functions in .Net Standard 2.0.

https://github.com/basicx-StrgV/WGet.NET/releases/tag/3.0.0-alpha2

The library now fully supports .Net Standard 2.0.  
If there are no problems, there will be no need for more pre-releases.  
Therefore the next release will probably be the full release.  
If the issue is not needed anymore, I will close it as soon as the version is fully released.

**Closed as completed** 2023-10-17 15:28 UTC
Labels: enhancement
